In [ ]:
import tensorflow as tf
print('Tensorflow version:', tf.__version__)

Tensorflow version: 2.20.0-dev20250604


In [8]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

c:\Python313\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.20008881,  0.5618883 ,  0.09929552, -0.6746368 , -0.01265191,
        -0.20036316, -0.3604582 , -0.23494269,  0.4657034 , -1.00272   ]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.12409853, 0.17819445, 0.11219995, 0.05174616, 0.10031699,
        0.08314814, 0.07084744, 0.08032206, 0.16185331, 0.03727292]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.4871314)

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9117 - loss: 0.3010
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9564 - loss: 0.1476
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9684 - loss: 0.1074
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9725 - loss: 0.0889
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9761 - loss: 0.0751


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9778 - loss: 0.0741


[0.07406866550445557, 0.9778000116348267]

In [17]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.6863490e-08, 2.7716800e-08, 2.6438287e-05, 2.4390228e-04,
        1.6494273e-11, 2.4626186e-07, 3.9762096e-13, 9.9969375e-01,
        7.6600935e-07, 3.4711498e-05],
       [1.0653195e-07, 4.7063135e-04, 9.9950433e-01, 1.6170554e-06,
        1.6535185e-18, 2.3351551e-05, 2.0755467e-08, 8.4930862e-14,
        1.5216452e-08, 3.3555604e-12],
       [2.9301171e-07, 9.9613684e-01, 5.6506152e-04, 1.5894426e-05,
        4.1381303e-05, 6.3644334e-06, 4.7524609e-06, 3.0391554e-03,
        1.8851775e-04, 1.6682769e-06],
       [9.9992812e-01, 7.7587137e-09, 5.5224693e-05, 9.8566026e-08,
        2.0660918e-08, 3.7727386e-06, 7.1518384e-06, 4.2876749e-07,
        5.8196736e-08, 5.2025780e-06],
       [5.0448222e-07, 1.5352619e-08, 4.5640527e-06, 3.2444138e-08,
        9.9379927e-01, 5.2690330e-06, 8.0124573e-07, 1.8154280e-05,
        1.5523476e-06, 6.1698509e-03]], dtype=float32)>